### PR TITLE
Implement service for transaction logging

### LINKED ISSUE #5: Implement Transaction Logging Service
## Overview
This service logs all swap transactions for record-keeping and analytics purposes.

## Payload
The service should handle incoming payloads with the following structure:

- `wallet_address` : The user's wallet address.
- `from_token` : The token swapped from.
- `to_token` : The token swapped to.
- `percentage` : The percentage of the `from_token` swapped.
- `amount_from` : The amount of `from_token` swapped.
- `amount_to` : The amount of `to_token` received.

## Functionality
- Record the transaction in the transactions_log table.
- Ensure data integrity (e.g., valid tokens and amounts).

## Acceptance Criteria
- All transaction data is logged accurately.

## Examples
**Input Payload:**

```json
{
  "wallet_address": "0xUserAddress",
  "from_token": "STRK",
  "to_token": "USDT",
  "percentage": 50,
  "amount_from": 500,
  "amount_to": 480
}
```
**Database Insert:**

- Insert into transactions_log:
- `wallet_address`: 0xUserAddress
- `from_token`: STRK
- `to_token`: USDT
- `percentage`: 50
- `amount_from`: 500
- `amount_to`: 480

## Dependencies
- Swap event from the smart contract.
- Database table: `transactions_log`.

### PR DESCRIPTION
**Pull request by codebestia**
Fixes #5

### CODE REVIEW

**Comment by codebestia** [comment]
> Hi @codebestia what's the status of this?

Hello @Abeeujah. PR ready for review. Please review.

**Comment by Abeeujah** [comment]
Hi, could you lint and format your code before you push? you're failing CI

**Comment by codebestia** [comment]
> Hi, could you lint and format your code before you push? you're failing CI

Done

**Comment by Abeeujah** [comment]
https://github.com/BlockheaderWeb3-Community/autoswappr-backend/actions/runs/12099115142/job/33736653371?pr=10
- Needless return
- Needless Borrow

**Comment by codebestia** [comment]
> https://github.com/BlockheaderWeb3-Community/autoswappr-backend/actions/runs/12099115142/job/33736653371?pr=10
> 
> * Needless return
> * Needless Borrow

Resolved

**Pull request merged**
